refactor(mistral): update safe_mode property and max temperature in C…
davidmigloz/langchain_dart pull request #300
Opened 2024-01-18 21:36 UTC by kndpt

…hatCompletionRequest

2024-01-18 22:18 UTC, davidmigloz requested changes
Thanks again for the PR!

I've added a couple of comments. Basically:
- The generated files have been generated in the wrong folder
- We don't need to update the version / release notes manually

The changes in the OpenAPI spec look good, so as soon as we fix those couple of things we can merge it 🙂

2024-01-18 22:18 UTC, davidmigloz commented on examples/docs_examples/pubspec.lock
> +    version: "0.0.3"
We do versioning automatically with melos, for now you can leave the old version
```suggestion
    version: "0.0.2+1"
```

2024-01-18 22:18 UTC, davidmigloz commented on packages/mistralai_dart/CHANGELOG.md
> +
The release notes are also automatically generated by melos from the commit title, so we don't need to edit them manually

2024-01-18 22:18 UTC, davidmigloz commented on packages/mistralai_dart/oas/lib/src/generated/client.dart
> +// coverage:ignore-file
I forgot to mention to run the `main.dart` from the `mistralai_dart` folder instead of from`oas`. 
Because now all the classes have been generated in `mistralai_dart/oas/lib/src/generated` instead of `packages/mistralai_dart/lib/src/generated`.

I should include a Makefile to avoid this issues, sorry!

Can you rerun the generation again so that it generates the classes in the right folder?

2024-01-18 22:18 UTC, davidmigloz commented on packages/mistralai_dart/pubspec.yaml
> +version: 0.0.2+2
We don't need to bump the version manually. It is done automatically when running `melos version`

```suggestion
version: 0.0.2+1
```

2024-01-19 08:04 UTC, kndpt commented on packages/mistralai_dart/oas/lib/src/generated/client.dart
> +// coverage:ignore-file
So sorry I didn't see that 
Thanks for your time !

2024-01-19 12:34 UTC, davidmigloz approved these changes
It's perfect now, thank you very much!

2024-01-19 12:42 UTC, merged

2024-01-20 11:45 UTC, davidmigloz commented
Released!
https://github.com/davidmigloz/langchain_dart/releases/tag/langchain-v0.3.3